development:
  sso_client: <%= ENV['SSO_CLIENT'] %>
  sso_secret: <%= ENV['SSO_SECRET'] %>
  sso_login_url: <%= ENV['SSO_LOGIN_URL'] %>
  sso_register_url: <%= ENV['SSO_REGISTER_URL'] %>
  sso_profile_url: <%= ENV['SSO_PROFILE_URL'] %>
  rezserve_base_url: <%= ENV['REZSERVE_BASE_URL'] %>
  rezserve_api_key: <%= ENV['REZSERVE_API_KEY'] %>